"""Profiling subagent - performance profiling and analysis."""

import logging
from typing import AsyncGenerator

from google.adk.agents import SequentialAgent
from google.adk.agents.invocation_context import InvocationContext
from google.adk.events import Event, EventActions

from auto_agent.callbacks import (
  load_profiling_script_to_state,
  load_single_kernel_to_state,
)
from auto_agent.config import get_thinking_planner, model_config
from auto_agent.constants import MODEL_NAME
from auto_agent.custom_types import CustomLlmAgent
from auto_agent.subagents.profiling import offline_tools
from auto_agent.subagents.profiling.kernel_profile import KernelProfiler
from auto_agent.subagents.profiling.prompts import (
  analyze_profile_prompt,
  gen_profiling_script,
  read_profiling_script_prompt,
)
from auto_agent.tools.file_tools import (
  filesystem_tool_r,
  write_profiling_script_tool,
)
from auto_agent.tools.tools import vertex_ai_rag_tool


# Profiling script generation agent - writes profiling script to file
def create_generate_profiling_script_agent(
  model_name: str = MODEL_NAME,
) -> CustomLlmAgent:
  return CustomLlmAgent(
    name="GenerateProfilingScriptAgent",
    model=model_name,
    generate_content_config=model_config,
    planner=get_thinking_planner("high"),
    instruction=gen_profiling_script.PROMPT,
    description="Generates a profiling script to identify performance bottlenecks in the kernel code and writes it to a file.",
    tools=[filesystem_tool_r, write_profiling_script_tool],
    before_agent_callback=load_single_kernel_to_state,
    include_contents="none",
  )


generate_profiling_script_agent = create_generate_profiling_script_agent()


# Read profiling script agent - loads the generated profiling script file contents into state
def create_read_profiling_script_agent(
  model_name: str = MODEL_NAME,
) -> CustomLlmAgent:
  return CustomLlmAgent(
    name="ReadProfilingScriptAgent",
    model=model_name,
    generate_content_config=model_config,
    instruction=read_profiling_script_prompt.PROMPT,
    description="Loads the generated profiling script file contents from disk into memory for execution.",
    before_agent_callback=load_profiling_script_to_state,
    include_contents="none",
  )


read_profiling_script_agent = create_read_profiling_script_agent()


# Profiling execution agent
def create_eval_profile_agent() -> KernelProfiler:
  return KernelProfiler(
    name="ProfileEvalAgent",
    input_key="profiling_script",
    output_key="profiling_results",
  )


eval_profile_agent = create_eval_profile_agent()


class SummarizeProfileAgent(CustomLlmAgent):
  """Custom agent that generates a summary and makes a boolean decision on improvement."""

  async def _run_async_impl(
    self, ctx: InvocationContext
  ) -> AsyncGenerator[Event, None]:
    # 1. Run the normal LLM summary generation
    async for event in super()._run_async_impl(ctx):
      yield event

    # 2. Retrieve the summary generated by the parent call
    summary = ctx.session.state.get("profiling_summary", "")

    # 3. Parse the decision from the summary
    needs_improvement = True  # Default fallback
    import re

    match = re.search(
      r"NEEDS[-_\s]?IMPROVEMENT\s*[:=]\s*(TRUE|FALSE|YES|NO)",
      summary,
      re.IGNORECASE,
    )
    if match:
      decision = match.group(1).upper()
      if decision in ["FALSE", "NO"]:
        needs_improvement = False
      elif decision in ["TRUE", "YES"]:
        needs_improvement = True
      logging.info(f"[{self.name}] Parsed decision '{decision}' from summary.")
    else:
      logging.warning(
        f"[{self.name}] Could not parse decision from summary. Defaulting to True."
      )

    # 4. Direct inject the boolean into state
    logging.info(
      f"[{self.name}] Agent decision: needs_improvement = {needs_improvement}"
    )
    yield Event(
      author=self.name,
      actions=EventActions(
        state_delta={"needs_improvement": needs_improvement}
      ),
    )


# Profiling summary agent
def create_summarize_profile_agent(
  model_name: str = MODEL_NAME,
) -> SummarizeProfileAgent:
  return SummarizeProfileAgent(
    name="SummarizeProfileAgent",
    model=model_name,
    generate_content_config=model_config,
    planner=get_thinking_planner("high"),
    instruction=analyze_profile_prompt.PROMPT,
    description=(
      "Summarizes the profiling results of the kernel and performs deep"
      " analysis using offline XProf tools."
    ),
    output_key="profiling_summary",
    include_contents="none",
    tools=[
      offline_tools.load_xplane_and_query,
      offline_tools.get_hlo_dump,
      offline_tools.create_chart_from_xplane,
      offline_tools.get_overview_page_metrics,
    ]
    + ([vertex_ai_rag_tool] if vertex_ai_rag_tool else []),
  )


summarize_profile_agent = create_summarize_profile_agent()


# Main profiling orchestrator agent
def create_profile_agent(model_name: str = MODEL_NAME) -> SequentialAgent:
  return SequentialAgent(
    name="ProfileAgentOrchestrator",
    sub_agents=[
      create_generate_profiling_script_agent(model_name),
      create_read_profiling_script_agent(model_name),
      create_eval_profile_agent(),
      create_summarize_profile_agent(model_name),
    ],
    description="Profiles the Pallas kernel to identify performance bottlenecks.",
  )


profile_agent = create_profile_agent()


__all__ = [
  "profile_agent",
  "generate_profiling_script_agent",
  "read_profiling_script_agent",
  "eval_profile_agent",
  "summarize_profile_agent",
]
